import axios from 'axios';
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react';
import { Video } from '../types'

interface IProps {
  videos: Video[];
}


const Home: NextPage<IProps> = ({ videos }) => {

  return (
    <div className='mx-auto'>
      <Head>
        <title>YouTube - Shorts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container snap-y snap-mandatory mt-[10rem] md:mt-[6rem] md:h-[40rem] md:w-[20rem] flex flex-col items-center overflow-hidden overflow-y-scroll">
        {videos.map((video) => (
          <div
            className="my-10 snap-center"
            key={video._id}
          >
            <video
              loop
              controls
              src={video.video.asset.url}
              className='w-[250px] md:w-full rounded-xl cursor-pointer'
            ></video>
          </div>
        ))}
      </div>
    </div>
  )
}

export default Home

export const getServerSideProps = async ({
  query: { topic },
}: {
  query: { topic: string };
}) => {

  let response = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/post`);

  if (topic) {
    response = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/discover/${topic}`);
  }

  return {
    props: { videos: response.data },
  };
};